import type { OfficeType } from '@/lib/classify';

export type Channel = 'office' | 'online';
export type Persona = 'general' | 'rider' | 'freelancer' | 'sme' | 'jobseeker' | 'welfare';

export type Service = {
  id: string;
  group: string;
  title: string;
  persona: Persona[];
  officeTypes: OfficeType[];
  docs: string[];
  fee: string;
  stdHours: string;
  channel: Channel[];
  officialUrl: string;
  hotline: string;
  lastVerified: string;
  locatorAvailable: boolean;
};

export const PERSONAS: { id: Persona; label: string; emoji: string }[] = [
  { id: 'general', label: 'ประชาชนทั่วไป', emoji: '👤' },
  { id: 'rider', label: 'คนขับ/ไรเดอร์', emoji: '🛵' },
  { id: 'freelancer', label: 'ฟรีแลนซ์/อาชีพอิสระ', emoji: '💻' },
  { id: 'sme', label: 'เจ้าของกิจการ/SME', emoji: '🏪' },
  { id: 'jobseeker', label: 'หางาน/ว่างงาน', emoji: '🔎' },
  { id: 'welfare', label: 'ผู้สูงอายุ/สวัสดิการ', emoji: '👵' },
];

export const SERVICES: Service[] = [
  {
    id: 'id_card',
    group: 'ทั่วไป/ครอบครัว',
    title: 'บัตรประชาชน',
    persona: ['general'],
    officeTypes: ['district', 'local'],
    docs: [],
    fee: '',
    stdHours: '',
    channel: ['office'],
    officialUrl: '',
    hotline: '',
    lastVerified: '',
    locatorAvailable: true,
  },
  {
    id: 'house_registration',
    group: 'ทั่วไป/ครอบครัว',
    title: 'ทะเบียนบ้าน',
    persona: ['general'],
    officeTypes: ['district', 'local'],
    docs: [],
    fee: '',
    stdHours: '',
    channel: ['office'],
    officialUrl: '',
    hotline: '',
    lastVerified: '',
    locatorAvailable: true,
  },
  {
    id: 'marriage',
    group: 'ทั่วไป/ครอบครัว',
    title: 'ทะเบียนสมรส/หย่า',
    persona: ['general'],
    officeTypes: ['district', 'local'],
    docs: [],
    fee: '',
    stdHours: '',
    channel: ['office'],
    officialUrl: '',
    hotline: '',
    lastVerified: '',
    locatorAvailable: true,
  },
  {
    id: 'birth_death',
    group: 'ทั่วไป/ครอบครัว',
    title: 'สูติบัตร/มรณบัตร',
    persona: ['general'],
    officeTypes: ['district', 'local'],
    docs: [],
    fee: '',
    stdHours: '',
    channel: ['office'],
    officialUrl: '',
    hotline: '',
    lastVerified: '',
    locatorAvailable: true,
  },
  {
    id: 'passport',
    group: 'เดินทาง',
    title: 'หนังสือเดินทาง (พาสปอร์ต)',
    persona: ['general'],
    officeTypes: ['passport'],
    docs: [],
    fee: '',
    stdHours: '',
    channel: ['office'],
    officialUrl: '',
    hotline: '',
    lastVerified: '',
    locatorAvailable: true,
  },
  {
    id: 'driving_license',
    group: 'คนขับ/ไรเดอร์',
    title: 'ใบขับขี่ (ทำ/ต่อ)',
    persona: ['rider', 'general'],
    officeTypes: ['dlt'],
    docs: [],
    fee: '',
    stdHours: '',
    channel: ['office'],
    officialUrl: '',
    hotline: '',
    lastVerified: '',
    locatorAvailable: true,
  },
  {
    id: 'vehicle_tax',
    group: 'คนขับ/ไรเดอร์',
    title: 'ทะเบียนรถ/ต่อภาษี/พรบ.',
    persona: ['rider', 'general'],
    officeTypes: ['dlt'],
    docs: [],
    fee: '',
    stdHours: '',
    channel: ['office', 'online'],
    officialUrl: '',
    hotline: '',
    lastVerified: '',
    locatorAvailable: true,
  },
  {
    id: 'tax_filing',
    group: 'ภาษี',
    title: 'ยื่นภาษี/ขอเลขผู้เสียภาษี',
    persona: ['freelancer', 'sme', 'general'],
    officeTypes: ['revenue'],
    docs: [],
    fee: '',
    stdHours: '',
    channel: ['office', 'online'],
    officialUrl: '',
    hotline: '',
    lastVerified: '',
    locatorAvailable: true,
  },
  {
    id: 'vat_registration',
    group: 'ภาษี',
    title: 'จดทะเบียนภาษีมูลค่าเพิ่ม (VAT)',
    persona: ['sme'],
    officeTypes: ['revenue'],
    docs: [],
    fee: '',
    stdHours: '',
    channel: ['office', 'online'],
    officialUrl: '',
    hotline: '',
    lastVerified: '',
    locatorAvailable: true,
  },
  {
    id: 'social_security_m40',
    group: 'ประกันสังคม',
    title: 'ประกันสังคม มาตรา 40',
    persona: ['freelancer', 'rider'],
    officeTypes: ['sso'],
    docs: [],
    fee: '',
    stdHours: '',
    channel: ['office', 'online'],
    officialUrl: '',
    hotline: '',
    lastVerified: '',
    locatorAvailable: true,
  },
  {
    id: 'employer_registration',
    group: 'ประกันสังคม',
    title: 'ขึ้นทะเบียนผู้ประกันตน/นายจ้าง',
    persona: ['sme'],
    officeTypes: ['sso'],
    docs: [],
    fee: '',
    stdHours: '',
    channel: ['office', 'online'],
    officialUrl: '',
    hotline: '',
    lastVerified: '',
    locatorAvailable: true,
  },
  {
    id: 'unemployment',
    group: 'แรงงาน',
    title: 'ขึ้นทะเบียนว่างงาน/หางาน',
    persona: ['jobseeker'],
    officeTypes: ['employment'],
    docs: [],
    fee: '',
    stdHours: '',
    channel: ['office', 'online'],
    officialUrl: '',
    hotline: '',
    lastVerified: '',
    locatorAvailable: true,
  },
  {
    id: 'skill_training',
    group: 'ฝีมือแรงงาน',
    title: 'ฝึกอาชีพ/ทดสอบมาตรฐานฝีมือ',
    persona: ['jobseeker', 'general'],
    officeTypes: ['skill'],
    docs: [],
    fee: '',
    stdHours: '',
    channel: ['office'],
    officialUrl: '',
    hotline: '',
    lastVerified: '',
    locatorAvailable: true,
  },
  {
    id: 'commercial_registration',
    group: 'SME',
    title: 'จดทะเบียนพาณิชย์',
    persona: ['sme'],
    officeTypes: ['district', 'local'],
    docs: [],
    fee: '',
    stdHours: '',
    channel: ['office'],
    officialUrl: '',
    hotline: '',
    lastVerified: '',
    locatorAvailable: true,
  },
  {
    id: 'company_registration',
    group: 'SME',
    title: 'จดทะเบียนบริษัท/ห้างหุ้นส่วน',
    persona: ['sme'],
    officeTypes: ['dbd'],
    docs: [],
    fee: '',
    stdHours: '',
    channel: ['office', 'online'],
    officialUrl: '',
    hotline: '',
    lastVerified: '',
    locatorAvailable: true,
  },
  {
    id: 'elderly_disability_allowance',
    group: 'สวัสดิการ',
    title: 'เบี้ยผู้สูงอายุ/คนพิการ',
    persona: ['welfare'],
    officeTypes: ['local'],
    docs: [],
    fee: '',
    stdHours: '',
    channel: ['office'],
    officialUrl: '',
    hotline: '',
    lastVerified: '',
    locatorAvailable: true,
  },
];
