import type { OfficeType } from '@/lib/classify';

export type Channel = 'office' | 'online';
export type Persona = 'general' | 'rider' | 'freelancer' | 'sme' | 'jobseeker' | 'welfare';

export type Service = {
  id: string;
  group: string;
  title: string;
  persona: Persona[];
  officeTypes: OfficeType[];
  docs: string[];
  fee: string;
  stdHours: string;
  channel: Channel[];
  officialUrl: string;
  hotline: string;
  lastVerified: string;
  locatorAvailable: boolean;
};

export const PERSONAS: { id: Persona; label: string; emoji: string }[] = [
  { id: 'general', label: 'ประชาชนทั่วไป', emoji: '👤' },
  { id: 'rider', label: 'คนขับ/ไรเดอร์', emoji: '🛵' },
  { id: 'freelancer', label: 'ฟรีแลนซ์/อาชีพอิสระ', emoji: '💻' },
  { id: 'sme', label: 'เจ้าของกิจการ/SME', emoji: '🏪' },
  { id: 'jobseeker', label: 'หางาน/ว่างงาน', emoji: '🔎' },
  { id: 'welfare', label: 'ผู้สูงอายุ/สวัสดิการ', emoji: '👵' },
];

export const SERVICES: Service[] = [
  {
    id: 'id_card',
    group: 'ทั่วไป/ครอบครัว',
    title: 'บัตรประชาชน',
    persona: ['general'],
    officeTypes: ['district', 'local'],
    docs: [
      'บัตรประชาชนเดิมหรือเอกสารราชการมีรูปถ่าย',
      'สำเนาทะเบียนบ้าน (กรณีทำบัตรครั้งแรก)',
      'หลักฐานแจ้งความบัตรหาย (กรณีบัตรหาย)',
    ],
    fee: 'ทำครั้งแรก/ต่ออายุ ไม่มีค่าธรรมเนียม; บัตรหาย/ชำรุด 100 บาท',
    stdHours: 'จันทร์–ศุกร์ 08:30–16:30 (ปิดเสาร์–อาทิตย์/วันหยุดราชการ)',
    channel: ['office'],
    officialUrl: 'https://www.bora.dopa.go.th',
    hotline: '1548',
    lastVerified: '2026-06-28',
    locatorAvailable: true,
  },
  {
    id: 'house_registration',
    group: 'ทั่วไป/ครอบครัว',
    title: 'ทะเบียนบ้าน',
    persona: ['general'],
    officeTypes: ['district', 'local'],
    docs: [
      'บัตรประชาชนผู้แจ้ง',
      'สำเนาทะเบียนบ้านฉบับเจ้าบ้าน (ท.ร.14)',
      'บัตรประชาชนเจ้าบ้าน',
      'หลักฐานการครอบครองที่พักอาศัย (สัญญาเช่า/โฉนด/หนังสือยินยอม)',
    ],
    fee: 'ไม่มีค่าธรรมเนียม (กรณีแจ้งเกินกำหนดมีค่าปรับ)',
    stdHours: 'จันทร์–ศุกร์ 08:30–16:30 (ปิดเสาร์–อาทิตย์/วันหยุดราชการ)',
    channel: ['office'],
    officialUrl: 'https://www.dopa.go.th/public_service/service_guide24/view434',
    hotline: '1548',
    lastVerified: '2026-06-28',
    locatorAvailable: true,
  },
  {
    id: 'marriage',
    group: 'ทั่วไป/ครอบครัว',
    title: 'ทะเบียนสมรส/หย่า',
    persona: ['general'],
    officeTypes: ['district', 'local'],
    docs: [
      'บัตรประชาชนคู่สมรสทั้งสองฝ่าย',
      'พยาน 2 คน พร้อมบัตรประชาชน',
      'สัญญาก่อนสมรส (ถ้ามี)',
      'เอกสารแปลภาษาไทยรับรองโดยกระทรวงการต่างประเทศ (กรณีคู่สมรสชาวต่างชาติ)',
    ],
    fee: 'ไม่มีค่าธรรมเนียม (จดในสำนักทะเบียน); นอกสำนักทะเบียน 200 บาท',
    stdHours: 'จันทร์–ศุกร์ 08:30–16:30 (ปิดเสาร์–อาทิตย์/วันหยุดราชการ)',
    channel: ['office'],
    officialUrl: 'https://www.dopa.go.th/public_service/service_guide230/view279',
    hotline: '1548',
    lastVerified: '2026-06-28',
    locatorAvailable: true,
  },
  {
    id: 'birth_death',
    group: 'ทั่วไป/ครอบครัว',
    title: 'สูติบัตร/มรณบัตร',
    persona: ['general'],
    officeTypes: ['district', 'local'],
    docs: [
      'บัตรประชาชนผู้แจ้ง',
      'สำเนาทะเบียนบ้านบิดาหรือมารดา (กรณีแจ้งเกิด)',
      'หนังสือรับรองการเกิดจากสถานพยาบาล (ท.ร.1/1) กรณีเกิดในโรงพยาบาล',
      'ใบรับรองหรือหนังสือรับรองการตายจากแพทย์/สถานพยาบาล (กรณีแจ้งตาย)',
    ],
    fee: 'ไม่มีค่าธรรมเนียม',
    stdHours: 'จันทร์–ศุกร์ 08:30–16:30 (ปิดเสาร์–อาทิตย์/วันหยุดราชการ)',
    channel: ['office'],
    officialUrl: 'https://www.dopa.go.th/public_service/service_guide24/view216',
    hotline: '1548',
    lastVerified: '2026-06-28',
    locatorAvailable: true,
  },
  {
    id: 'passport',
    group: 'เดินทาง',
    title: 'หนังสือเดินทาง (พาสปอร์ต)',
    persona: ['general'],
    officeTypes: ['passport'],
    docs: [
      'บัตรประชาชนตัวจริง',
      'หนังสือเดินทางเล่มเดิม (กรณีต่ออายุหรือเล่มเต็ม)',
      'สำหรับผู้เยาว์: สูติบัตร บัตรประชาชนบิดา-มารดา และสำเนาทะเบียนบ้าน',
    ],
    fee: 'เล่ม 5 ปี 1,000 บาท; เล่ม 10 ปี 1,500 บาท',
    stdHours: 'จันทร์–ศุกร์ 08:30–16:30 (ปิดเสาร์–อาทิตย์/วันหยุดราชการ)',
    channel: ['office'],
    officialUrl: 'https://consular.mfa.go.th/th/publicservice/doc4passport',
    hotline: '02 572 8442',
    lastVerified: '2026-06-28',
    locatorAvailable: true,
  },
  {
    id: 'driving_license',
    group: 'คนขับ/ไรเดอร์',
    title: 'ใบขับขี่ (ทำ/ต่อ)',
    persona: ['rider', 'general'],
    officeTypes: ['dlt'],
    docs: [
      'บัตรประชาชนตัวจริง',
      'ใบรับรองแพทย์ (อายุไม่เกิน 1 เดือน)',
      'ใบขับขี่เดิม (กรณีต่ออายุ)',
      'หลักฐานผ่านการอบรม DLT e-Learning (กรณีทำใหม่)',
    ],
    fee: 'ทำใหม่รถยนต์ 305 บาท; ต่ออายุรถยนต์ 505 บาท; ทำใหม่รถจักรยานยนต์ 205 บาท; ต่ออายุรถจักรยานยนต์ 255 บาท',
    stdHours: 'จันทร์–ศุกร์ 08:30–16:30 (ปิดเสาร์–อาทิตย์/วันหยุดราชการ)',
    channel: ['office'],
    officialUrl: 'https://www.dlt.go.th/th/driving-license',
    hotline: '1584',
    lastVerified: '2026-06-28',
    locatorAvailable: true,
  },
  {
    id: 'vehicle_tax',
    group: 'คนขับ/ไรเดอร์',
    title: 'ทะเบียนรถ/ต่อภาษี/พรบ.',
    persona: ['rider', 'general'],
    officeTypes: ['dlt'],
    docs: [
      'สมุดคู่มือจดทะเบียนรถ (เล่มทะเบียน)',
      'กรมธรรม์ พ.ร.บ. ที่ยังไม่หมดอายุ',
      'ใบรับรองการตรวจสภาพรถ ตรอ. (เฉพาะรถยนต์อายุเกิน 7 ปี หรือรถจักรยานยนต์เกิน 5 ปี)',
      'บัตรประชาชนเจ้าของรถ (กรณียื่นด้วยตนเอง)',
    ],
    fee: 'ขึ้นอยู่กับประเภทและขนาดเครื่องยนต์ (รถยนต์ส่วนบุคคลทั่วไปประมาณ 300–1,650 บาท/ปี)',
    stdHours: 'จันทร์–ศุกร์ 08:30–16:30 (ออนไลน์ตลอด 24 ชั่วโมง)',
    channel: ['office', 'online'],
    officialUrl: 'https://eservice.dlt.go.th',
    hotline: '1584',
    lastVerified: '2026-06-28',
    locatorAvailable: true,
  },
  {
    id: 'tax_filing',
    group: 'ภาษี',
    title: 'ยื่นภาษี/ขอเลขผู้เสียภาษี',
    persona: ['freelancer', 'sme', 'general'],
    officeTypes: ['revenue'],
    docs: [
      'บัตรประชาชน',
      'หนังสือรับรองการหักภาษี ณ ที่จ่าย (50 ทวิ)',
      'เอกสารหลักฐานรายได้และค่าลดหย่อน',
      'แบบ ภ.ง.ด.90 หรือ ภ.ง.ด.91 (กรณียื่นที่สำนักงานสรรพากร)',
    ],
    fee: 'ไม่มีค่าธรรมเนียม',
    stdHours: 'จันทร์–ศุกร์ 08:30–16:30 (ออนไลน์ตลอด 24 ชั่วโมง)',
    channel: ['office', 'online'],
    officialUrl: 'https://www.rd.go.th/272.html',
    hotline: '1161',
    lastVerified: '2026-06-28',
    locatorAvailable: true,
  },
  {
    id: 'vat_registration',
    group: 'ภาษี',
    title: 'จดทะเบียนภาษีมูลค่าเพิ่ม (VAT)',
    persona: ['sme'],
    officeTypes: ['revenue'],
    docs: [
      'แบบคำขอจดทะเบียนภาษีมูลค่าเพิ่ม (ภ.พ.01) จำนวน 3 ชุด',
      'บัตรประชาชนหรือหนังสือรับรองนิติบุคคล',
      'หลักฐานที่ตั้งสถานประกอบการ (สัญญาเช่า/โฉนด/สำเนาทะเบียนบ้าน)',
    ],
    fee: 'ไม่มีค่าธรรมเนียม',
    stdHours: 'จันทร์–ศุกร์ 08:30–16:30 (ออนไลน์ตลอด 24 ชั่วโมง)',
    channel: ['office', 'online'],
    officialUrl: 'https://www.rd.go.th/7058.html',
    hotline: '1161',
    lastVerified: '2026-06-28',
    locatorAvailable: true,
  },
  {
    id: 'social_security_m40',
    group: 'ประกันสังคม',
    title: 'ประกันสังคม มาตรา 40',
    persona: ['freelancer', 'rider'],
    officeTypes: ['sso'],
    docs: [
      'แบบคำขอสมัครเป็นผู้ประกันตนมาตรา 40 (สปส.1-40)',
      'บัตรประชาชนตัวจริง',
      'สมุดบัญชีธนาคาร (กรณีสมัครจ่ายสมทบผ่านธนาคาร)',
    ],
    fee: 'ไม่มีค่าธรรมเนียมสมัคร; เงินสมทบ 70/100/300 บาท/เดือน (3 ทางเลือก)',
    stdHours: 'จันทร์–ศุกร์ 08:30–16:30 (ออนไลน์ตลอด 24 ชั่วโมง)',
    channel: ['office', 'online'],
    officialUrl: 'https://www.sso.go.th',
    hotline: '1506',
    lastVerified: '2026-06-28',
    locatorAvailable: true,
  },
  {
    id: 'employer_registration',
    group: 'ประกันสังคม',
    title: 'ขึ้นทะเบียนผู้ประกันตน/นายจ้าง',
    persona: ['sme'],
    officeTypes: ['sso'],
    docs: [
      'แบบขึ้นทะเบียนนายจ้าง สปส.1-01',
      'แผนที่ตั้งและภาพถ่ายสถานประกอบการ',
      'บัตรประชาชนผู้มีอำนาจลงนาม',
      'สัญญาเช่าหรือหนังสือยินยอมให้ใช้สถานที่',
    ],
    fee: 'ไม่มีค่าธรรมเนียม',
    stdHours: 'จันทร์–ศุกร์ 08:30–16:30 (ปิดเสาร์–อาทิตย์/วันหยุดราชการ)',
    channel: ['office', 'online'],
    officialUrl: 'https://www.sso.go.th',
    hotline: '1506',
    lastVerified: '2026-06-28',
    locatorAvailable: true,
  },
  {
    id: 'unemployment',
    group: 'แรงงาน',
    title: 'ขึ้นทะเบียนว่างงาน/หางาน',
    persona: ['jobseeker'],
    officeTypes: ['employment'],
    docs: [
      'บัตรประชาชน',
      'หนังสือรับรองออกจากงาน (สปส.6-09) หรือหนังสือเลิกจ้าง',
      'สำเนาสมุดบัญชีธนาคาร',
    ],
    fee: 'ไม่มีค่าธรรมเนียม',
    stdHours: 'จันทร์–ศุกร์ 08:30–16:30 (ออนไลน์ตลอด 24 ชั่วโมง)',
    channel: ['office', 'online'],
    officialUrl: 'https://e-service.doe.go.th',
    hotline: '1694',
    lastVerified: '2026-06-28',
    locatorAvailable: true,
  },
  {
    id: 'skill_training',
    group: 'ฝีมือแรงงาน',
    title: 'ฝึกอาชีพ/ทดสอบมาตรฐานฝีมือ',
    persona: ['jobseeker', 'general'],
    officeTypes: ['skill'],
    docs: [
      'บัตรประชาชน',
      'แบบคำขอรับการฝึกอบรม',
      'รูปถ่าย 1 นิ้ว (กรณีทดสอบมาตรฐานฝีมือ)',
      'หลักฐานการศึกษาหรือประสบการณ์ (ถ้ามี)',
    ],
    fee: 'ไม่มีค่าธรรมเนียมสำหรับหลักสูตรที่รัฐจัด',
    stdHours: 'จันทร์–ศุกร์ 08:30–16:30 (ปิดเสาร์–อาทิตย์/วันหยุดราชการ)',
    channel: ['office'],
    officialUrl: 'https://www.dsd.go.th',
    hotline: '02 245 1707',
    lastVerified: '2026-06-28',
    locatorAvailable: true,
  },
  {
    id: 'commercial_registration',
    group: 'SME',
    title: 'จดทะเบียนพาณิชย์',
    persona: ['sme'],
    officeTypes: ['district', 'local'],
    docs: [
      'บัตรประชาชน',
      'แบบคำขอจดทะเบียนพาณิชย์ (ทพ.)',
      'สำเนาทะเบียนบ้านหรือหลักฐานที่อยู่สถานประกอบการ',
      'หลักฐานการครอบครองสถานที่ (สัญญาเช่า/หนังสือยินยอม)',
      'แผนที่สถานที่ประกอบการ',
    ],
    fee: '50 บาท',
    stdHours: 'จันทร์–ศุกร์ 08:30–16:30 (ปิดเสาร์–อาทิตย์/วันหยุดราชการ)',
    channel: ['office'],
    officialUrl: 'https://www.dbd.go.th',
    hotline: '1570',
    lastVerified: '2026-06-28',
    locatorAvailable: true,
  },
  {
    id: 'company_registration',
    group: 'SME',
    title: 'จดทะเบียนบริษัท/ห้างหุ้นส่วน',
    persona: ['sme'],
    officeTypes: ['dbd'],
    docs: [
      'แบบคำขอจดทะเบียน (บอจ.1 สำหรับบริษัทจำกัด หรือ หส.1 สำหรับห้างหุ้นส่วน)',
      'หนังสือบริคณห์สนธิ (บอจ.2) กรณีจดทะเบียนบริษัทจำกัด',
      'สำเนาบัตรประชาชนกรรมการ/ผู้ถือหุ้น/หุ้นส่วนทุกคน',
      'แผนที่ตั้งและภาพถ่ายสำนักงาน',
      'หนังสือยินยอมให้ใช้สถานที่',
    ],
    fee: 'ห้างหุ้นส่วน 1,000 บาท; บริษัทจำกัดคำนวณตามทุนจดทะเบียน',
    stdHours: 'จันทร์–ศุกร์ 08:30–16:30 (ปิดเสาร์–อาทิตย์/วันหยุดราชการ)',
    channel: ['office', 'online'],
    officialUrl: 'https://www.dbd.go.th',
    hotline: '1570',
    lastVerified: '2026-06-28',
    locatorAvailable: true,
  },
  {
    id: 'elderly_disability_allowance',
    group: 'สวัสดิการ',
    title: 'เบี้ยผู้สูงอายุ/คนพิการ',
    persona: ['welfare'],
    officeTypes: ['local'],
    docs: [
      'บัตรประชาชน',
      'สำเนาทะเบียนบ้าน (ท.ร.14)',
      'สมุดบัญชีธนาคาร (กรณีขอรับเงินผ่านธนาคาร)',
      'บัตรประจำตัวคนพิการ (กรณีผู้พิการ)',
    ],
    fee: 'ไม่มีค่าธรรมเนียม',
    stdHours: 'จันทร์–ศุกร์ 08:30–16:30 (ปิดเสาร์–อาทิตย์/วันหยุดราชการ)',
    channel: ['office'],
    officialUrl: 'https://www.dop.go.th/th/know/13/328',
    hotline: '02 642 4336',
    lastVerified: '2026-06-28',
    locatorAvailable: true,
  },
];
